version: '3'
services:
  nextjs-ts:
    build: ./Dockerfiles/node/
    container_name: nextjs-ts
    tty: true
    volumes:
      #- ./:/usr/src/app
      - .:/usr/src/app
      #command: npm run dev
    ports:
      - "3000:3000"
